#!/usr/bin/env python3
"""Build every Neon Sumi port from design/tokens.json.

    python3 tools/build_themes.py           write design/tokens.css and themes/*, and sync the
                                            palette lines of the Obsidian theme and Ghostty config
    python3 tools/build_themes.py --check   also list colour literals in the repo that are not tokens; exit 1 if any

Standard library only, Python 3.9+. Every generated file says so; edit the tokens instead.
Files are only rewritten when their content changes, so a no-op run leaves git clean.
"""
import json
import math
import os
import plistlib
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOKENS = os.path.join(ROOT, "design", "tokens.json")
NOTE = "Generated by tools/build_themes.py from design/tokens.json. Edit the tokens, not this file."
CHANGED = []


# ── tokens ─────────────────────────────────────────────────────────────────────
def load(path=TOKENS):
    """Flatten the DTCG tree to {"color.magenta": "#ff2ec4", ...} with references resolved."""
    with open(path, encoding="utf-8") as fh:
        raw = json.load(fh)
    flat, refs = {}, {}

    def walk(node, prefix):
        for key, val in node.items():
            if key.startswith("$") or not isinstance(val, dict):
                continue
            if "$value" in val:
                flat[prefix + key] = val["$value"]
            else:
                walk(val, prefix + key + ".")

    walk(raw, "")

    def resolve(key, seen=()):
        val = flat[key]
        m = re.fullmatch(r"\{([^}]+)\}", val) if isinstance(val, str) else None
        if not m:
            return val
        target = m.group(1)
        if target in seen or target not in flat:
            raise SystemExit("tokens.json: bad reference %s -> {%s}" % (key, target))
        refs[key] = target
        return resolve(target, seen + (key,))

    tokens = {k: resolve(k) for k in flat}
    meta = raw.get("$extensions", {}).get("neon-sumi", {})
    return tokens, refs, meta


def rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def hexa(c):
    return "#%02x%02x%02x" % tuple(max(0, min(255, int(round(v)))) for v in c)


def mix(a, b, t):
    return hexa(tuple(x + (y - x) * t for x, y in zip(rgb(a), rgb(b))))


def put(rel, data):
    """Write a file under ROOT only if its bytes change."""
    path = os.path.join(ROOT, rel)
    data = data.encode("utf-8") if isinstance(data, str) else data
    if os.path.exists(path):
        with open(path, "rb") as fh:
            if fh.read() == data:
                return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(data)
    CHANGED.append(rel)


class Palette:
    """T.magenta -> "#ff2ec4"; T.a("magenta", .2) -> "#ff2ec433"; T["role.text.muted"] -> hex."""

    def __init__(self, tokens):
        self.t = tokens

    def __getattr__(self, name):
        return self.t["color." + name.replace("_", "-")]

    def __getitem__(self, key):
        return self.t[key]

    def a(self, name, alpha):
        base = name if name.startswith("#") else self.t["color." + name.replace("_", "-")]
        return base + "%02x" % int(round(alpha * 255))

    def role(self, path):
        return self.t["role." + path]

    def ansi(self, n):
        return self.t["ansi.%d" % n]


# ── design/tokens.css ──────────────────────────────────────────────────────────
NEON = ("magenta", "violet", "blue", "cyan", "teal", "mint", "amber", "gold", "red")


def css_name(key):
    parts = key.split(".")
    if parts[0] == "color":
        return "--ns-" + parts[1]
    if parts[0] in ("role", "statusline"):
        return "--ns-" + "-".join(parts[1:])
    if parts[0] == "font":
        return "--ns-" + {"family": "font", "weight": "weight", "size": "size", "leading": "leading"}[parts[1]] + "-" + parts[2]
    if parts[0] == "motion":
        return "--ns-" + ("ease" if parts[1] == "ease" else "duration-" + parts[1])
    return "--ns-" + "-".join(parts)


def css_value(key, val, refs):
    if key in refs:
        return "var(%s)" % css_name(refs[key])
    if isinstance(val, list) and key.startswith("font.family"):
        return ", ".join('"%s"' % f if " " in f else f for f in val)
    if isinstance(val, list):
        return "cubic-bezier(%s)" % ", ".join(str(v) for v in val)
    return str(val)


def build_css(tokens, refs):
    out = ["/* %s */" % NOTE, "", ":root {", "  color-scheme: dark;"]
    group = None
    for key, val in tokens.items():
        if key.startswith("glow."):
            continue
        head = key.split(".")[0] if not key.startswith(("role.", "font.")) else ".".join(key.split(".")[:2])
        if head != group:
            out.append("")
            group = head
        out.append("  %s: %s;" % (css_name(key), css_value(key, val, refs)))
    out.append("")
    out.append("  /* rgb triplets, for rgba(var(--ns-rgb-teal), .3) */")
    for key, val in tokens.items():
        if key.startswith("color."):
            out.append("  --ns-rgb-%s: %s;" % (key[6:], "%d, %d, %d" % rgb(val)))
    out.append("")
    out.append("  /* glow: the only elevation */")
    for name in NEON:
        kind = "glow.text" if name in ("magenta", "violet", "blue", "red") else "glow.text-bright"
        out.append("  --ns-glow-%s: %s;" % (name, tokens[kind].replace("{rgb}", "var(--ns-rgb-%s)" % name)))
    for kind in ("button", "tube", "lit", "stage"):
        out.append("  --ns-glow-%s: %s;" % (kind, tokens["glow." + kind].replace("{rgb}", "var(--ns-rgb-magenta)")))
    out.append("}")
    out.append("")
    out.append("@media (prefers-reduced-motion: reduce) {")
    out.append("  :root { --ns-duration-quick: 0ms; --ns-duration-flow: 0ms; }")
    out.append("}")
    put("design/tokens.css", "\n".join(out) + "\n")


# ── Zed ────────────────────────────────────────────────────────────────────────
def build_zed(T, meta):
    s, c = T.role, T
    syn = lambda k: s("syntax." + k)
    st = lambda col, style=None, weight=None: dict(color=col, **({"font_style": style} if style else {}),
                                                     **({"font_weight": weight} if weight else {}))
    names = ("black", "red", "green", "yellow", "blue", "magenta", "cyan", "white")
    style = {
        "background.appearance": "opaque",
        "accents": [s("heading.h%d" % i) for i in range(1, 7)],
        "background": c.deep,
        "surface.background": c.deep,
        "elevated_surface.background": c.raised,
        "border": c.line,
        "border.variant": c.line,
        "border.focused": c.a("magenta", .6),
        "border.selected": c.magenta,
        "border.transparent": "#00000000",
        "border.disabled": c.line,
        "element.background": c.raised,
        "element.hover": c.raised_hi,
        "element.active": c.overlay,
        "element.selected": c.a("magenta", .16),
        "element.disabled": c.raised,
        "drop_target.background": c.a("magenta", .1),
        "ghost_element.background": "#00000000",
        "ghost_element.hover": c.a("paper", .05),
        "ghost_element.active": c.a("paper", .09),
        "ghost_element.selected": c.a("magenta", .16),
        "ghost_element.disabled": "#00000000",
        "text": c.paper,
        "text.muted": c.stone,
        "text.placeholder": c.ink_hi,
        "text.disabled": c.ink,
        "text.accent": c.magenta,
        "icon": c.soft,
        "icon.muted": c.stone,
        "icon.disabled": c.ink,
        "icon.placeholder": c.ink_hi,
        "icon.accent": c.magenta,
        "status_bar.background": c.deep,
        "title_bar.background": c.deep,
        "title_bar.inactive_background": c.deep,
        "toolbar.background": c.sumi,
        "tab_bar.background": c.deep,
        "tab.inactive_background": c.deep,
        "tab.active_background": c.sumi,
        "search.match_background": c.a("amber", .3),
        "search.active_match_background": c.a("amber", .55),
        "panel.background": c.deep,
        "panel.focused_border": c.a("magenta", .6),
        "panel.indent_guide": c.line,
        "panel.indent_guide_hover": c.ink,
        "panel.indent_guide_active": c.ink_hi,
        "pane.focused_border": c.a("magenta", .4),
        "pane_group.border": c.line,
        "scrollbar.thumb.background": c.a("ink", .35),
        "scrollbar.thumb.hover_background": c.a("ink", .6),
        "scrollbar.thumb.active_background": c.a("magenta", .45),
        "scrollbar.thumb.border": "#00000000",
        "scrollbar.track.background": "#00000000",
        "scrollbar.track.border": "#00000000",
        "minimap.thumb.background": c.a("ink", .2),
        "minimap.thumb.hover_background": c.a("ink", .35),
        "minimap.thumb.active_background": c.a("magenta", .25),
        "editor.foreground": c.paper,
        "editor.background": c.sumi,
        "editor.gutter.background": c.sumi,
        "editor.subheader.background": c.raised,
        "editor.active_line.background": c.sumi_hi,
        "editor.highlighted_line.background": c.raised,
        "editor.line_number": c.ink,
        "editor.active_line_number": c.soft,
        "editor.hover_line_number": c.stone,
        "editor.invisible": c.line_hi,
        "editor.wrap_guide": c.line,
        "editor.active_wrap_guide": c.line_hi,
        "editor.indent_guide": c.line,
        "editor.indent_guide_active": c.ink,
        "editor.document_highlight.read_background": c.a("violet", .14),
        "editor.document_highlight.write_background": c.a("violet", .24),
        "editor.document_highlight.bracket_background": c.a("magenta", .14),
        "link_text.hover": c.cyan,
        "version_control.added": s("git.added"),
        "version_control.modified": s("git.modified"),
        "version_control.deleted": s("git.deleted"),
        "version_control.renamed": s("git.renamed"),
        "version_control.conflict": s("git.conflict"),
        "version_control.ignored": s("git.ignored"),
        "version_control.word_added": c.a("mint", .2),
        "version_control.word_deleted": c.a("red", .2),
        "version_control.conflict_marker.ours": c.a("mint", .12),
        "version_control.conflict_marker.theirs": c.a("blue", .12),
        "terminal.background": c.sumi,
        "terminal.foreground": c.paper,
        "terminal.bright_foreground": c.bright,
        "terminal.dim_foreground": c.stone,
    }
    for i, n in enumerate(names):
        style["terminal.ansi." + n] = T.ansi(i)
        style["terminal.ansi.bright_" + n] = T.ansi(i + 8)
        style["terminal.ansi.dim_" + n] = mix(T.ansi(i), c.sumi, .35)
    for name, col in (("conflict", c.amber), ("created", c.mint), ("deleted", c.red), ("error", c.red),
                      ("hidden", c.ink), ("hint", c.violet), ("ignored", c.ink), ("info", c.cyan),
                      ("modified", c.blue), ("predictive", c.ink_hi), ("renamed", c.violet),
                      ("success", c.mint), ("unreachable", c.ink_hi), ("warning", c.amber)):
        style[name] = col
        style[name + ".background"] = mix(c.sumi, col, .1)
        style[name + ".border"] = mix(c.sumi, col, .45)
    style["players"] = [{"cursor": h, "background": h, "selection": h + "3d"}
                        for h in (c.magenta, c.cyan, c.mint, c.violet, c.amber, c.blue, c.teal, c.red)]
    style["players"][0]["selection"] = c.selection
    style["syntax"] = {
        "attribute": st(syn("property"), "italic"),
        "boolean": st(syn("constant")),
        "comment": st(syn("comment"), "italic"),
        "comment.doc": st(syn("comment"), "italic"),
        "constant": st(syn("constant")),
        "constructor": st(syn("type")),
        "diff.minus": st(s("git.deleted")),
        "diff.plus": st(s("git.added")),
        "embedded": st(c.paper),
        "emphasis": st(c.soft, "italic"),
        "emphasis.strong": st(c.bright, None, 700),
        "enum": st(syn("type")),
        "function": st(syn("function")),
        "hint": st(c.ink_hi, "italic"),
        "keyword": st(syn("keyword")),
        "label": st(c.violet),
        "link_text": st(s("link.internal")),
        "link_uri": st(s("link.external")),
        "namespace": st(syn("type")),
        "number": st(syn("number")),
        "operator": st(syn("operator")),
        "predictive": st(c.ink_hi, "italic"),
        "preproc": st(syn("decorator")),
        "primary": st(syn("text")),
        "property": st(syn("property")),
        "punctuation": st(syn("punctuation")),
        "punctuation.bracket": st(syn("punctuation")),
        "punctuation.delimiter": st(syn("punctuation")),
        "punctuation.list_marker": st(c.magenta),
        "punctuation.markup": st(c.ink_hi),
        "punctuation.special": st(syn("keyword")),
        "selector": st(syn("type")),
        "selector.pseudo": st(syn("keyword")),
        "string": st(syn("string")),
        "string.escape": st(syn("regexp")),
        "string.regex": st(syn("regexp")),
        "string.special": st(syn("regexp")),
        "string.special.symbol": st(syn("constant")),
        "tag": st(syn("tag")),
        "text.literal": st(c.mint),
        "title": st(s("heading.h1"), None, 700),
        "type": st(syn("type")),
        "variable": st(syn("text")),
        "variable.parameter": st(syn("text"), "italic"),
        "variable.special": st(syn("self"), "italic"),
        "variant": st(syn("type")),
    }
    family = {"$schema": "https://zed.dev/schema/themes/v0.2.0.json", "name": meta.get("theme", "Neon Sumi"),
              "author": meta.get("author", "Danneftw1"),
              "themes": [{"name": meta.get("theme", "Neon Sumi"), "appearance": "dark", "style": style}]}
    put("themes/zed/neon-sumi.json", json.dumps(family, indent=2) + "\n")


# ── Claude Code (/theme) ──────────────────────────────────────────────────────
def build_claude_code(T, meta):
    """A custom theme (code.claude.com/docs/en/terminal-config#create-a-custom-theme). Shipped inside the
    plugin, so /theme lists it once the plugin is installed; or copy it to ~/.claude/themes/."""
    c = T
    lift = lambda h: mix(h, c.bright, .4)
    o = {
        "claude": c.magenta, "claudeShimmer": c.core,
        "text": c.paper, "inverseText": c.sumi,
        "inactive": c.stone, "inactiveShimmer": c.soft, "subtle": c.ink_hi,
        "suggestion": c.cyan, "permission": c.blue, "permissionShimmer": lift(c.blue), "remember": c.teal,
        "success": c.mint, "error": c.red, "warning": c.amber, "warningShimmer": c.gold, "merged": c.violet,
        "promptBorder": c.ink, "promptBorderShimmer": c.stone,
        "planMode": c.teal, "autoAccept": c.violet, "bashBorder": c.magenta, "ide": c.cyan,
        "fastMode": c.gold, "fastModeShimmer": lift(c.gold), "effortUltra": c.magenta,
        "diffAdded": mix(c.sumi, c.mint, .16), "diffRemoved": mix(c.sumi, c.red, .18),
        "diffAddedDimmed": mix(c.sumi, c.mint, .08), "diffRemovedDimmed": mix(c.sumi, c.red, .09),
        "diffAddedWord": mix(c.sumi, c.mint, .34), "diffRemovedWord": mix(c.sumi, c.red, .38),
        "userMessageBackground": c.raised_hi, "userMessageBackgroundHover": c.overlay,
        "bashMessageBackgroundColor": mix(c.sumi, c.magenta, .08), "memoryBackgroundColor": mix(c.sumi, c.teal, .07),
        "selectionBg": c.selection,
        "rate_limit_fill": c.cyan, "rate_limit_empty": T["statusline.meter.track"],
        "briefLabelYou": c.cyan, "briefLabelClaude": c.magenta,
        "background": c.sumi, "composerSidebarBackground": c.deep,
        "skill": c.violet, "autoAcceptShimmer": lift(c.violet),
        "claudeBlue_FOR_SYSTEM_SPINNER": c.blue, "claudeBlueShimmer_FOR_SYSTEM_SPINNER": lift(c.blue),
        "professionalBlue": c.blue, "chromeYellow": c.gold,
        "clawd_body": c.magenta, "clawd_background": c.sumi,
    }
    for name, h in (("red", c.red), ("blue", c.blue), ("green", c.mint), ("yellow", c.gold), ("purple", c.violet),
                    ("orange", c.amber), ("pink", c.magenta), ("cyan", c.cyan)):
        o[name + "_FOR_SUBAGENTS_ONLY"] = h
    for name, h in (("red", c.red), ("orange", c.amber), ("yellow", c.gold), ("green", c.mint), ("blue", c.blue),
                    ("indigo", c.violet), ("violet", c.magenta)):
        o["rainbow_" + name] = h
        o["rainbow_%s_shimmer" % name] = lift(h)
    theme = {"name": meta.get("theme", "Neon Sumi"), "base": "dark", "overrides": o}
    put("plugins/neon-sumi/themes/neon-sumi.json", json.dumps(theme, indent=2) + "\n")


# ── iTerm2 ─────────────────────────────────────────────────────────────────────
def build_iterm(T, meta):
    def col(h, alpha=1.0):
        r, g, b = rgb(h)
        return {"Red Component": r / 255.0, "Green Component": g / 255.0, "Blue Component": b / 255.0,
                "Alpha Component": alpha, "Color Space": "sRGB"}
    c = T
    d = {"Ansi %d Color" % i: col(T.ansi(i)) for i in range(16)}
    d.update({
        "Background Color": col(c.sumi), "Foreground Color": col(c.paper), "Bold Color": col(c.bright),
        "Cursor Color": col(c.magenta), "Cursor Text Color": col(c.sumi), "Cursor Guide Color": col(c.sumi_hi, .6),
        "Selection Color": col(c.selection), "Selected Text Color": col(c.bright), "Link Color": col(c.cyan),
        "Badge Color": col(c.magenta, .5), "Underline Color": col(c.magenta),
    })
    put("themes/iterm2/%s.itermcolors" % meta.get("theme", "Neon Sumi"), plistlib.dumps(d))


# ── themes/README.md ──────────────────────────────────────────────────────────
def build_readme(meta):
    name = meta.get("theme", "Neon Sumi")
    rows = [
        ("Claude Code", "`plugins/neon-sumi/themes/neon-sumi.json`", "ships with the plugin: `/theme` → %s (or copy it to `~/.claude/themes/`)" % name),
        ("Zed", "`themes/zed/neon-sumi.json`", "copy to `~/.config/zed/themes/`, then pick %s" % name),
        ("iTerm2", "`themes/iterm2/%s.itermcolors`" % name, "Settings → Profiles → Colors → Color Presets → Import"),
        ("Ghostty", "`plugins/neon-sumi/statusline/ghostty/neon-sumi.ghostty`", "add `config-file = ~/.claude/neon-sumi/ghostty/neon-sumi.ghostty` to the Ghostty config (palette kept in step)"),
        ("Obsidian", "`obsidian/theme/`", "copy to `.obsidian/themes/%s/` (palette kept in step)" % name),
        ("Web", "`design/tokens.css`", "`--ns-*` custom properties"),
    ]
    out = ["# %s everywhere" % name, "",
           "Every file here is generated from `design/tokens.json`. Change a colour there, run "
           "`python3 tools/build_themes.py`, and every port follows; `--check` lists colours in the repo that are not tokens.", "",
           "| Tool | File | Install |", "| --- | --- | --- |"]
    out += ["| %s | %s | %s |" % r for r in rows]
    out += ["", "<!-- %s -->" % NOTE]
    put("themes/README.md", "\n".join(out) + "\n")


# ── keep the hand-written ports in step ───────────────────────────────────────
def _retint(rel, anchors, T):
    """anchors: [(regex with one hex group, token key)]. Where a named line in the file holds a colour that
    differs from its token, replace that colour everywhere in the file (hex and r, g, b forms)."""
    path = os.path.join(ROOT, rel)
    if not os.path.exists(path):
        return
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    swaps = {}
    for pattern, key in anchors:
        for m in re.finditer(pattern, text, re.M | re.I):
            old, new = m.group(1).lower(), T[key].lower()
            if old != new:
                swaps[old] = new
    for old, new in swaps.items():
        text = re.sub(re.escape(old), new, text, flags=re.I)
        o, n = rgb(old), rgb(new)
        text = re.sub(r"\b%d,(\s*)%d,(\s*)%d\b" % o, lambda m: "%d,%s%d,%s%d" % (n[0], m.group(1), n[1], m.group(2), n[2]), text)
    if swaps:
        put(rel, text)
        print("  retinted %s: %s" % (rel, ", ".join("%s→%s" % kv for kv in swaps.items())))


def sync_ports(T):
    names = ["deep", "sumi", "raised", "line", "ink", "stone", "soft", "paper", "bright", "magenta", "violet",
             "teal", "cyan", "blue", "mint", "amber", "red", "selection"]
    base = {"00": "sumi", "05": "sumi-hi", "10": "raised", "20": "raised-hi", "25": "overlay", "30": "line",
            "35": "line-hi", "40": "ink", "50": "ink-hi", "60": "stone", "70": "soft", "100": "paper"}
    ext = {"red": "red", "orange": "amber", "yellow": "gold", "green": "mint", "cyan": "cyan", "blue": "blue",
           "purple": "violet", "pink": "magenta"}
    obsidian = [(r"--ns-%s:\s*(#[0-9a-f]{6})" % n, "color." + n) for n in names]
    obsidian += [(r"--color-base-%s:\s*(#[0-9a-f]{6})" % k, "color." + v) for k, v in base.items()]
    obsidian += [(r"--color-%s:\s*(#[0-9a-f]{6})" % k, "color." + v) for k, v in ext.items()]
    _retint("obsidian/theme/theme.css", obsidian, T)
    ghostty = [(r"^background = (#[0-9a-f]{6})", "role.surface.ground"), (r"^foreground = (#[0-9a-f]{6})", "role.text.normal"),
               (r"^cursor-color = (#[0-9a-f]{6})", "color.magenta"), (r"^selection-background = (#[0-9a-f]{6})", "color.selection"),
               (r"^selection-foreground = (#[0-9a-f]{6})", "color.bright")]
    ghostty += [(r"^palette = %d=(#[0-9a-f]{6})" % i, "ansi.%d" % i) for i in range(16)]
    _retint("plugins/neon-sumi/statusline/ghostty/neon-sumi.ghostty", ghostty, T)


# ── --check: colour literals that are not tokens ──────────────────────────────
CHECK = ["plugins/neon-sumi/statusline/statusline.py", "plugins/neon-sumi/statusline/cockpit.py",
         "plugins/neon-sumi/statusline/subagent.sh", "plugins/neon-sumi/icon.svg", "docs/index.html",
         "obsidian/theme/theme.css", "obsidian/snippets/neon-sumi-terminal.css",
         "plugins/neon-sumi/statusline/ghostty/neon-sumi.ghostty"]
XTERM = {240: "#585858", 244: "#808080", 252: "#d0d0d0", 214: "#ffaf00", 203: "#ff5f5f"}


def check(T):
    known = {}
    for k, v in T.items():
        if isinstance(v, str) and re.fullmatch(r"#[0-9a-fA-F]{6}", v):
            known.setdefault(rgb(v), k)
    palette = {k: rgb(v) for k, v in T.items() if k.startswith("color.")}
    found = 0
    for rel in CHECK:
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            continue
        with open(path, encoding="utf-8", errors="replace") as fh:
            text = fh.read()
        text = re.sub(r"data:[^\"')\s]{200,}", "", text)
        hits = {}
        for lineno, line in enumerate(text.split("\n"), 1):
            cands = [rgb(h) for h in re.findall(r"#([0-9a-fA-F]{6})\b", line)]
            cands += [t for t in (tuple(int(v) for v in m) for m in re.findall(
                r"\(\s*(\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3})\s*[,)]", line)) if max(t) >= 20]
            cands += [rgb(XTERM[int(n)]) for n in re.findall(r"38;5;(\d+)", line) if int(n) in XTERM]
            for col in cands:
                if max(col) > 255 or col in known or col == (0, 0, 0) or col == (255, 255, 255):
                    continue
                hits.setdefault(col, []).append(lineno)
        if not hits:
            continue
        print("\n%s" % rel)
        for col, lines in sorted(hits.items(), key=lambda kv: kv[1][0]):
            near, dist = min(((k, math.dist(col, v)) for k, v in palette.items()), key=lambda kv: kv[1])
            print("  %s  ≈ %-15s Δ%-5.1f line %s" % (hexa(col), near[6:], dist, ", ".join(str(n) for n in lines[:6])))
            found += 1
    print("\n%d colour literal%s off the tokens." % (found, "" if found == 1 else "s"))
    return found


def main():
    tokens, refs, meta = load()
    T = Palette(tokens)
    build_css(tokens, refs)
    build_zed(T, meta)
    build_claude_code(T, meta)
    build_iterm(T, meta)
    build_readme(meta)
    sync_ports(T)
    for rel in CHANGED:
        print("  wrote " + rel)
    if not CHANGED:
        print("  everything already matches design/tokens.json")
    if "--check" in sys.argv and check(tokens):
        sys.exit(1)


if __name__ == "__main__":
    main()
